name: React Continous Integration

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs_on: ubuntu_latest
    steps:
      - uses: actions/chechout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm start:test
      - run: npm run build:prod
